# Generated by Django 4.2.2 on 2023-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='employee.skill'),
        ),
    ]
