# Generated by Django 4.2.2 on 2023-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y'),
        ),
    ]
